#ifndef CHEM_CONSTANTS_H
#define CHEM_CONSTANTS_H

#include "udf.h"

#define CHEM_EPS (1.0e-30)

/* Required behavior flags */
#ifndef CHEM_USE_ADJACENT_CELL_CACHE
#define CHEM_USE_ADJACENT_CELL_CACHE 1
#endif
#ifndef CHEM_ENFORCE_SITE_BALANCE_PROJECTION
#define CHEM_ENFORCE_SITE_BALANCE_PROJECTION 1
#endif
#ifndef CHEM_USE_NUMERICAL_JACOBIAN
#define CHEM_USE_NUMERICAL_JACOBIAN 1
#endif
#ifndef CHEM_ENABLE_DEBUG_LOG
#define CHEM_ENABLE_DEBUG_LOG 0
#endif
#ifndef CHEM_USE_REFERENCE_ETA_FOR_SELECTED_REACTIONS
#define CHEM_USE_REFERENCE_ETA_FOR_SELECTED_REACTIONS 1
#endif
#ifndef CHEM_APPLY_WASHCOAT_ON_EXPORT_ONLY
#define CHEM_APPLY_WASHCOAT_ON_EXPORT_ONLY 1
#endif

#define SITE_DEN_TOT (2.72E-8)
#define Pt_Frac (0.75)
#define SITE_DEN_Pt (SITE_DEN_TOT*Pt_Frac)
#define SITE_DEN_Rh (SITE_DEN_TOT*(1.0-Pt_Frac))
#define Wash_F (70.0)

#define CHEM_MAX_NEWTON_ITERS 10
#define CHEM_NEWTON_TOL 1e-10

#endif
